name: navigation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.2
  flutter_tts: ^4.2.3
  geolocator: ^14.0.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  image: ^4.5.4
  logger: ^2.5.0
  mapbox_maps_flutter: ^2.8.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/download.png"


flutter:
  uses-material-design: true

  assets:
    - assets/udsm_locations.geojson
    - assets/images/
    - assets/icons/
    - assets/image/
  


