name: navigation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.1
  http: ^1.4.0
  logger: ^2.5.0
  mapbox_maps_flutter: ^2.8.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/udsm_locations.geojson
    - assets/images/


